[package]
name = "leetcode-cat-and-mouse"
version = "0.1.0"
authors = ["mayaming <mayaming1983@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
